### ISSUE TITLE
Warning sezione "Lettura Dati" app

### ISSUE THREAD

**Issue by angelomarzucco** [pasoppido87/Smart_Green_House#2]
Il sistema, se viene premuto ripetutamente il tasto di aggiornamento, va in errore. Bisogna eliminare tale problematica. @A88Russo è necessario correggere il bug introdotto.

**Comment by A88Russo** [comment]
@angelomarzucco Il bug è stato corretto con il [commit 9ae2611](https://github.com/pasoppido87/Smart_Green_House/commit/9ae26113cf677a7b7117768857a45201788f4bb1)
